export const DICTIONARY = {
  TR: {
    inputPlaceholder: "Linkleri buraya yapıştırın (Max 10 satır)...", analyzeBtn: "Analiz Et", activeTab: "AKTİF", finishedTab: "BİTENLER", logsTab: "LOGLAR", pauseAll: "Tümünü Duraklat", resumeAll: "Tümünü Devam Ettir", analyzingMsg: "Bağlantı inceleniyor...", optionsLoaded: "Medya Seçenekleri Yüklendi", error: "Hata", warning: "Uyarı", unknown: "Bilinmiyor", skipped: "ATLANDI", formatSelect: "Format Seçiniz", subSelect: "Altyazı Tercihi", tabSelect: "Sekme Seçiniz", contentCount: "Toplam içerik sayısı :", rangeSelect: "Aralık seç :", downloadAll: "Hepsini indir", cancel: "İptal", addToQueue: "Kuyruğa Ekle", queued: "Kuyrukta bekliyor...", downloading: "İndiriliyor...", paused: "Duraklatıldı", completed: "Tamamlandı", open: "Aç", share: "Paylaş / Kopyala", showInFolder: "Klasörde Göster", settingsTitle: "Ayarlar", downloadLoc: "İNDİRME KONUMU", locNotSet: "Klasör Seçiniz (Zorunlu)", locSet: "Klasör Konumu Ayarlandı", smartFolder: "Akıllı Klasörleme", smartFolderSub: "Dosyaları türlerine göre alt klasörlere ayırır.", autoUpdateEngine: "İndirme Motorunu Otomatik Güncelle", autoUpdateEngineSub: "Yeni sürüm bulunduğunda sormadan indirip kurar.", maxConcurrent: "MAKS. İNDİRME", subPref: "ALTYAZI TERCİH SIRASI", lang1: "1. Dil", lang2: "2. Dil", lang3: "3. Dil", auth: "KİMLİK DOĞRULAMA", cookiesNotSet: "cookies.txt Seçiniz", cookiesSet: "cookies.txt Eklendi", darkTheme: "Karanlık Tema Aktif", lightTheme: "Aydınlık Tema", sortTitle: "Seçenekler", sortOptions: "SIRALAMA", sortNewOld: "Yeniden Eskiye", sortAZ: "İsme Göre (A-Z)", sortSize: "Boyuta Göre", actions: "İŞLEMLER", clearTab: "Geçerli Sekmeyi Temizle", close: "Kapat", helpTitle: "Yardım Konuları", emptyTab: "Bu sekmede gösterilecek kayıt yok.", selectLanguage: "Dil Seçiniz", noSub: "Altyazı İndirme", autoSeq: "Oto Sıralı - Varsa", onlyFirst: "Sadece", bestVideo: "En İyi Kalite", ifNotAvail: "(Yoksa atlanır)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• Temel Kullanım:", helpBasicDesc: "Uygulama temel bir indirme yöneticisinin yanı sıra Youtube, Instagram gibi media içeriklerini tek tek yada toplu indirme yeteneklerine sahiptir. Youtube uygulamasında herhangi bir videoyu paylaş dediğinizde çıkan uygulama listesinden Ridm seçerseniz, otomatik olarak link analiz edilerek indirmeye hazır hale gelebilmektedir. Uygulama içerisinde tek seferde enter ile ayrılmış max 10 link ekleyebilirsiniz. Playlist ve Kanal indirme kartlarında bulunan format seçiminde en iyi kaliteyi seçtiğinizde kaynak sunucudaki en yüksek çözünürlük ve kalitedeki videoları indir anlamına gelir. 2160p ve 1080p formatlarından birini seçtiğinizde toplu indirme esnasında seçili çözünürlükte video yoksa o dosyayı indirmeyip sıradakine geç anlamına gelir. Hem video hem de ses dosyalarını altyazı/lirik gömülü olarak indirebilirsiniz.", helpBasicWarn: "İndirme yapabilmek için Ayarlar menüsünden indirmelerin kaydedileceği klasörü seçmeniz gerekmektedir.\n\nİndirme işleminin arka planda kesintisiz devam edebilmesi için uygulamanın Android güç seçeneklerinde pil kullanımının kısıtlama yok olarak ayarlanması gerekmektedir.",
    helpSmartTitle: "• Akıllı Klasörleme:", helpSmartDesc: "Aktif edildiğinde indirmeleriniz türlerine göre (Videos, Audio vb.) otomatik olarak alt klasörlere ayrılır.",
    helpSubTitle: "• Altyazı Tercihi (Toplu İndirmeler):", helpSubDesc: "Ayarlar menüsündeki 'Altyazı Tercih Sırası', Kanal ve Playlist gibi toplu indirmelerde her video için size tek tek altyazı sorma zahmetinden kurtarır. İndirme ekranında 'Oto Sıralı' seçeneğini işaretlerseniz; sistem her videoda 1. dile bakar, bulamazsa 2. dile geçer ve bulduğunu gömer. 'Sadece' seçeneği ise yalnızca belirttiğiniz 1. dil videoda mevcutsa indirir.",
    helpCookiesTitle: "• Cookies / Kimlik Doğrulama:", helpCookiesDesc: "Instagram veya yaş kısıtlamalı YouTube içeriklerini indirebilmek için hesabınızı uygulamaya tanıtmanız gerekir:\n1. Bilgisayarınızdan veya telefonunuzdaki tarayıcının eklenti mağazasından (Chrome, Firefox Browser ADD-ONS vb.) \"cookies.txt\" eklentisini kurun.\n2. Tarayıcıdan YouTube veya Instagram'a girip oturum açın.\n3. Eklenti simgesine tıklayıp Download seçeneği ile cookies.txt dosyasını indirerek telefonunuzdaki istediğiniz bir konuma kopyalayın.\n4. Uygulama Ayarlarından \"cookies.txt Seçiniz\" butonuna tıklayıp bu dosyayı uygulamaya bağlayın.",
    
    supportTitle: "İletişim & Destek", supportDesc: "Ridm tamamen ücretsiz ve açık kaynaklıdır. Projeye destek olmak için bağış yapabilir, iletişim için aşağıdaki mail adresinden ulaşabilirsiniz.", quote: "Cömertin yemeği şifadır, cimrinin yemeği hastalıktır.", donateBtn: "Destek Ol", copied: "Kopyalandı!", copy: "Kopyala",
    
    exitTitle: "Çıkış Yap", exitGraceful: "Yarım kalanları bitir ve çık", exitForce: "Zorla çıkış yap", errNoInternet: "İnternet bağlantınız yok.", errLocation: "Lütfen önce Ayarlar menüsünden indirme klasörü seçiniz.", errDuplicate: "Bu link mevcut oturumda var.", errServer: "Sunucu yanıt vermedi."
  },
  EN: {
    inputPlaceholder: "Paste links here (Max 10 lines)...", analyzeBtn: "Analyze", activeTab: "ACTIVE", finishedTab: "FINISHED", logsTab: "LOGS", pauseAll: "Pause All", resumeAll: "Resume All", analyzingMsg: "Analyzing...", optionsLoaded: "Media Options Loaded", error: "Error", warning: "Warning", unknown: "Unknown", skipped: "SKIPPED", formatSelect: "Select Format", subSelect: "Subtitle Preference", tabSelect: "Select Tab", contentCount: "Total content count :", rangeSelect: "Select range :", downloadAll: "Download all", cancel: "Cancel", addToQueue: "Add to Queue", queued: "Waiting in queue...", downloading: "Downloading...", paused: "Paused", completed: "Completed", open: "Open", share: "Share / Copy", showInFolder: "Show in Folder", settingsTitle: "Settings", downloadLoc: "DOWNLOAD LOCATION", locNotSet: "Select Folder", locSet: "Folder Location Set", smartFolder: "Smart Folders", smartFolderSub: "Automatically sort files into subfolders.", autoUpdateEngine: "Auto-Update Engine", autoUpdateEngineSub: "Downloads and installs new versions without asking.", maxConcurrent: "MAX DOWNLOADS", subPref: "SUBTITLE ORDER", lang1: "1st Lang", lang2: "2nd Lang", lang3: "3rd Lang", auth: "AUTHENTICATION", cookiesNotSet: "Select cookies.txt", cookiesSet: "cookies.txt Added", darkTheme: "Dark Theme", lightTheme: "Light Theme", sortTitle: "Options", sortOptions: "SORTING", sortNewOld: "Newest to Oldest", sortAZ: "By Name (A-Z)", sortSize: "By Size", actions: "ACTIONS", clearTab: "Clear Current Tab", close: "Close", helpTitle: "Help Topics", emptyTab: "No records to display.", selectLanguage: "Select Language", noSub: "No Subtitles", autoSeq: "Auto Sequence", onlyFirst: "Only", bestVideo: "Best Quality", ifNotAvail: "(Skip if unavailable)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• Basic Usage:", helpBasicDesc: "In addition to being a basic download manager, the app can download media from platforms like YouTube and Instagram individually or in bulk. If you choose Ridm from the share menu when sharing a video in the YouTube app, the link is analyzed automatically and gets ready to download. You can add up to 10 links at once, separated by Enter. On the Playlist and Channel download cards, choosing the best-quality format means downloading the highest resolution and quality available on the source server. Choosing 2160p or 1080p means that, during a bulk download, any file not available in that resolution is skipped instead of being downloaded. Both video and audio files can be downloaded with embedded subtitles/lyrics.", helpBasicWarn: "You must select a download folder from Settings to be able to download.\n\nIn order for the download process to continue uninterrupted in the background, the app's battery usage must be set to 'Unrestricted' in Android power options.",
    helpSmartTitle: "• Smart Folders:", helpSmartDesc: "When activated, downloads are sorted into subfolders by type.",
    helpSubTitle: "• Subtitle Preference:", helpSubDesc: "The system checks for the 1st language, then the 2nd, and embeds the first one it finds automatically.",
    helpCookiesTitle: "• Cookies / Authentication:", helpCookiesDesc: "To download Instagram or age-restricted YouTube content, you must link your account:\n1. Install a \"cookies.txt\" extension (Chrome, Firefox Browser ADD-ONS, etc.) from your browser's extension store on your PC or phone.\n2. Log in to YouTube or Instagram from the browser.\n3. Click on the extension icon and use the Download option to save the cookies.txt file to any location on your phone.\n4. Go to App Settings, click the \"Select cookies.txt\" button, and link this file to the application.",
    
    supportTitle: "Contact & Support", supportDesc: "Ridm is completely free and open-source. You can donate to support the project and contact us via the email address below.", quote: "The generous' food heals, the miser's food sickens.", donateBtn: "Donate", copied: "Copied!", copy: "Copy",
    
    exitTitle: "Exit", exitGraceful: "Finish pending and exit", exitForce: "Force Exit", errNoInternet: "No internet connection.", errLocation: "Please select a download folder first.", errDuplicate: "Link already exists.", errServer: "Server error."
  },
  AR: {
    inputPlaceholder: "الصق الروابط هنا...", analyzeBtn: "تحليل", activeTab: "نشط", finishedTab: "مكتمل", logsTab: "سجلات", pauseAll: "إيقاف الكل", resumeAll: "استئناف الكل", analyzingMsg: "جارٍ التحليل...", optionsLoaded: "تم التحميل", error: "خطأ", warning: "تحذير", unknown: "مجهول", skipped: "تم التخطي", formatSelect: "اختر التنسيق", subSelect: "الترجمة", tabSelect: "التبويب", contentCount: "إجمالي المحتوى :", rangeSelect: "النطاق :", downloadAll: "تنزيل الكل", cancel: "إلغاء", addToQueue: "طابور", queued: "في الانتظار...", downloading: "تنزيل...", paused: "موقوف", completed: "مكتمل", open: "فتح", share: "مشاركة", showInFolder: "في المجلد", settingsTitle: "إعدادات", downloadLoc: "موقع التنزيل", locNotSet: "حدد مجلد", locSet: "تم التعيين", smartFolder: "مجلدات ذكية", smartFolderSub: "فرز تلقائي.", autoUpdateEngine: "تحديث المحرك تلقائيًا", autoUpdateEngineSub: "يُنزّل ويُثبّت الإصدارات الجديدة دون سؤال.", maxConcurrent: "الحد الأقصى", subPref: "ترتيب الترجمة", lang1: "لغة 1", lang2: "لغة 2", lang3: "لغة 3", auth: "المصادقة", cookiesNotSet: "حدد cookies.txt", cookiesSet: "تمت الإضافة", darkTheme: "مظهر داكن", lightTheme: "مظهر فاتح", sortTitle: "خيارات", sortOptions: "فرز", sortNewOld: "الأحدث", sortAZ: "حسب الاسم", sortSize: "حسب الحجم", actions: "إجراءات", clearTab: "مسح السجل", close: "إغلاق", helpTitle: "المساعدة", emptyTab: "لا يوجد محتوى.", selectLanguage: "اختر اللغة", noSub: "بدون ترجمة", autoSeq: "تسلسل تلقائي", onlyFirst: "فقط", bestVideo: "أفضل جودة", ifNotAvail: "(تخطي إذا غير متوفر)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• الاستخدام الأساسي:", helpBasicDesc: "بالإضافة إلى كونه مدير تنزيل أساسيًا، يمكن للتطبيق تنزيل الوسائط من منصات مثل YouTube وInstagram بشكل فردي أو جماعي. إذا اخترت Ridm من قائمة المشاركة عند مشاركة فيديو في تطبيق YouTube، يتم تحليل الرابط تلقائيًا ويصبح جاهزًا للتنزيل. يمكنك إضافة حتى 10 روابط دفعة واحدة، مفصولة بمفتاح Enter. في بطاقات تنزيل قوائم التشغيل والقنوات، يعني اختيار أفضل جودة تنزيل أعلى دقة وجودة متاحة على الخادم المصدر. يعني اختيار 2160p أو 1080p أنه أثناء التنزيل الجماعي، يتم تخطي أي ملف غير متوفر بتلك الدقة بدلاً من تنزيله. يمكن تنزيل ملفات الفيديو والصوت مع ترجمات/كلمات مضمّنة.", helpBasicWarn: "يجب عليك تحديد مجلد التنزيل من قائمة الإعدادات لتتمكن من التنزيل.\n\nلكي تستمر عملية التنزيل دون انقطاع في الخلفية، يجب ضبط استخدام بطارية التطبيق على 'غير مقيد' في خيارات طاقة Android.",
    helpSmartTitle: "• المجلدات الذكية:", helpSmartDesc: "فرز التنزيلات تلقائياً في مجلدات.",
    helpSubTitle: "• تفضيل الترجمة:", helpSubDesc: "دمج الترجمات تلقائياً حسب اللغات المفضلة.",
    helpCookiesTitle: "• ملفات تعريف الارتباط / المصادقة:", helpCookiesDesc: "لتنزيل محتوى Instagram أو محتوى YouTube المقيد بالفئة العمرية، يجب ربط حسابك:\n1. قم بتثبيت إضافة \"cookies.txt\" من متجر إضافات المتصفح (Chrome، Firefox ADD-ONS وما إلى ذلك) على الكمبيوتر أو الهاتف.\n2. قم بتسجيل الدخول إلى YouTube أو Instagram من المتصفح.\n3. انقر على أيقونة الإضافة واستخدم خيار Download لحفظ ملف cookies.txt في أي مكان بهاتفك.\n4. انتقل إلى إعدادات التطبيق، وانقر على زر \"حدد cookies.txt\" لربط هذا الملف.",
    
    supportTitle: "التواصل والدعم", supportDesc: "تطبيق Ridm مجاني تمامًا ومفتوح المصدر. يمكنك التبرع لدعم المشروع والتواصل عبر عنوان البريد الإلكتروني أدناه.", quote: "طَعَامُ الْجَوَادِ دَوَاءٌ، وَطَعَامُ الْبَخِيلِ دَاءٌ", donateBtn: "ادعمنا", copied: "تم النسخ!", copy: "ينسخ",
    
    exitTitle: "خروج", exitGraceful: "إنهاء المعلق", exitForce: "خروج إجباري", errNoInternet: "لا يوجد إنترنت.", errLocation: "حدد مجلد التنزيل.", errDuplicate: "الرابط موجود.", errServer: "خطأ في الخادم."
  },
  ZH: {
    inputPlaceholder: "在此处粘贴链接...", analyzeBtn: "分析", activeTab: "活跃", finishedTab: "已完成", logsTab: "日志", pauseAll: "全部暂停", resumeAll: "全部恢复", analyzingMsg: "分析中...", optionsLoaded: "选项已加载", error: "错误", warning: "警告", unknown: "未知", skipped: "已跳过", formatSelect: "选择格式", subSelect: "字幕", tabSelect: "标签页", contentCount: "总数 :", rangeSelect: "范围 :", downloadAll: "下载全部", cancel: "取消", addToQueue: "加入队列", queued: "等待中...", downloading: "下载中...", paused: "已暂停", completed: "已完成", open: "打开", share: "分享", showInFolder: "显示文件夹", settingsTitle: "设置", downloadLoc: "下载位置", locNotSet: "选择文件夹", locSet: "位置已设置", smartFolder: "智能文件夹", smartFolderSub: "自动分类文件。", autoUpdateEngine: "自动更新引擎", autoUpdateEngineSub: "发现新版本时自动下载并安装，不再询问。", maxConcurrent: "最大下载数", subPref: "字幕顺序", lang1: "第一语言", lang2: "第二语言", lang3: "第三语言", auth: "身份验证", cookiesNotSet: "选择 cookies.txt", cookiesSet: "已添加", darkTheme: "深色主题", lightTheme: "浅色主题", sortTitle: "选项", sortOptions: "排序", sortNewOld: "从新到旧", sortAZ: "按名称", sortSize: "按大小", actions: "操作", clearTab: "清除记录", close: "关闭", helpTitle: "帮助", emptyTab: "无记录。", selectLanguage: "选择语言", noSub: "无字幕", autoSeq: "自动顺序", onlyFirst: "仅", bestVideo: "最佳质量", ifNotAvail: "(如不可用则跳过)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• 基本用法：", helpBasicDesc: "除了基本的下载管理功能外，本应用还可以单独或批量下载来自 YouTube、Instagram 等平台的媒体内容。在 YouTube 应用中分享视频时，如果从分享列表中选择 Ridm，链接将被自动分析并准备好下载。您一次最多可以添加 10 个以回车分隔的链接。在播放列表和频道下载卡片的格式选择中，选择最佳质量表示下载源服务器上可用的最高分辨率和质量的视频。选择 2160p 或 1080p 表示在批量下载时，如果没有所选分辨率的视频，将跳过该文件并继续下一个。视频和音频文件都可以嵌入字幕/歌词进行下载。", helpBasicWarn: "您必须从设置中选择下载文件夹才能进行下载。\n\n为了使下载过程在后台不间断地继续，必须在 Android 电源选项中将应用程序的电池使用设置为“无限制”。",
    helpSmartTitle: "• 智能文件夹：", helpSmartDesc: "按类型自动分类文件。",
    helpSubTitle: "• 字幕偏好：", helpSubDesc: "自动查找并嵌入首选字幕。",
    helpCookiesTitle: "• 身份验证：", helpCookiesDesc: "要下载 Instagram 或受年龄限制的 YouTube 内容，您必须链接您的帐户：\n1. 在电脑或手机浏览器的扩展商店（Chrome、Firefox ADD-ONS 等）中安装 \"cookies.txt\" 扩展程序。\n2. 从浏览器登录 YouTube 或 Instagram。\n3. 单击扩展图标并使用 Download 选项将 cookies.txt 文件保存到手机上的任意位置。\n4. 转到应用设置，单击 \"选择 cookies.txt\" 按钮，并将此文件链接到应用。",
    
    supportTitle: "联系与支持", supportDesc: "Ridm完全免费且开源。您可以捐赠以支持该项目，并通过以下电子邮件地址与我们联系。", quote: "慷慨者的食物是良药，吝啬者的食物是毒药。", donateBtn: "捐赠", copied: "已复制！", copy: "复制",
    
    exitTitle: "退出", exitGraceful: "完成待处理", exitForce: "强制退出", errNoInternet: "无网络。", errLocation: "请选择文件夹。", errDuplicate: "链接已存在。", errServer: "服务器错误。"
  },
  HI: {
    inputPlaceholder: "लिंक पेस्ट करें...", analyzeBtn: "विश्लेषण", activeTab: "सक्रिय", finishedTab: "पूरा", logsTab: "लॉग", pauseAll: "रोकें", resumeAll: "फिर शुरू करें", analyzingMsg: "विश्लेषण हो रहा है...", optionsLoaded: "विकल्प लोड हुए", error: "त्रुटि", warning: "चेतावनी", unknown: "अज्ञात", skipped: "छोड़ दिया", formatSelect: "प्रारूप चुनें", subSelect: "उपशीर्षक", tabSelect: "टैब", contentCount: "कुल :", rangeSelect: "सीमा :", downloadAll: "सभी डाउनलोड करें", cancel: "रद्द करें", addToQueue: "कतार में जोड़ें", queued: "प्रतीक्षा...", downloading: "डाउनलोड...", paused: "रोका गया", completed: "पूरा हुआ", open: "खोलें", share: "साझा करें", showInFolder: "फ़ोल्डर दिखाएं", settingsTitle: "सेटिंग्स", downloadLoc: "स्थान", locNotSet: "फ़ोल्डर चुनें", locSet: "सेट किया गया", smartFolder: "स्मार्ट फोल्डर", smartFolderSub: "स्वतः सॉर्ट करें।", autoUpdateEngine: "इंजन ऑटो-अपडेट", autoUpdateEngineSub: "नया संस्करण मिलने पर बिना पूछे डाउनलोड और इंस्टॉल करता है।", maxConcurrent: "अधिकतम डाउनलोड", subPref: "उपशीर्षक क्रम", lang1: "भाषा 1", lang2: "भाषा 2", lang3: "भाषा 3", auth: "प्रमाणीकरण", cookiesNotSet: "cookies.txt चुनें", cookiesSet: "जोड़ा गया", darkTheme: "डार्क", lightTheme: "लाइट", sortTitle: "विकल्प", sortOptions: "क्रमबद्ध", sortNewOld: "नवीनतम", sortAZ: "नाम से", sortSize: "आकार से", actions: "कार्रवाई", clearTab: "साफ़ करें", close: "बंद करें", helpTitle: "मदद", emptyTab: "कोई रिकॉर्ड नहीं।", selectLanguage: "भाषा चुनें", noSub: "कोई उपशीर्षक नहीं", autoSeq: "ऑटो अनुक्रम", onlyFirst: "केवल", bestVideo: "सर्वश्रेष्ठ", ifNotAvail: "(उपलब्ध न होने पर छोड़ें)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• मूल उपयोग:", helpBasicDesc: "यह ऐप एक बुनियादी डाउनलोड मैनेजर होने के साथ-साथ YouTube, Instagram जैसे प्लेटफ़ॉर्म से मीडिया को अलग-अलग या बल्क में डाउनलोड कर सकता है। YouTube ऐप में किसी वीडियो को शेयर करते समय शेयर सूची से Ridm चुनने पर, लिंक अपने आप विश्लेषित होकर डाउनलोड के लिए तैयार हो जाता है। आप एक बार में Enter से अलग किए गए अधिकतम 10 लिंक जोड़ सकते हैं। प्लेलिस्ट और चैनल डाउनलोड कार्ड में सर्वश्रेष्ठ गुणवत्ता चुनने का मतलब है स्रोत सर्वर पर उपलब्ध सबसे अधिक रिज़ॉल्यूशन और गुणवत्ता वाला वीडियो डाउनलोड करना। 2160p या 1080p में से कोई एक चुनने का मतलब है कि बल्क डाउनलोड के दौरान, चयनित रिज़ॉल्यूशन में वीडियो न होने पर उस फ़ाइल को छोड़कर अगली फ़ाइल पर जाना। वीडियो और ऑडियो दोनों फ़ाइलों को एम्बेडेड सबटाइटल/लिरिक्स के साथ डाउनलोड किया जा सकता है।", helpBasicWarn: "डाउनलोड करने के लिए आपको सेटिंग्स से एक डाउनलोड फ़ोल्डर चुनना होगा।\n\nडाउनलोड प्रक्रिया को पृष्ठभूमि में निर्बाध रूप से जारी रखने के लिए, एंड्रॉइड पावर विकल्पों में ऐप के बैटरी उपयोग को 'अप्रतिबंधित' (Unrestricted) पर सेट किया जाना चाहिए。",
    helpSmartTitle: "• स्मार्ट फ़ोल्डर:", helpSmartDesc: "स्मार्ट फ़ोल्डर स्वतः सॉर्ट करता है।",
    helpSubTitle: "• उपशीर्षक प्राथमिकता:", helpSubDesc: "स्वचालित रूप से उपशीर्षक एम्बेड करेगा।",
    helpCookiesTitle: "• प्रमाणीकरण:", helpCookiesDesc: "Instagram या आयु-प्रतिबंधित YouTube सामग्री डाउनलोड करने के लिए, आपको अपना खाता लिंक करना होगा:\n1. अपने पीसी या फ़ोन पर ब्राउज़र के एक्सटेंशन स्टोर (Chrome, Firefox ADD-ONS, आदि) से \"cookies.txt\" एक्सटेंशन इंस्टॉल करें।\n2. ब्राउज़र से YouTube या Instagram में लॉग इन करें।\n3. एक्सटेंशन आइकन पर क्लिक करें और cookies.txt फ़ाइल को अपने फ़ोन पर किसी भी स्थान पर सहेजने के लिए Download विकल्प का उपयोग करें।\n4. ऐप सेटिंग्स पर जाएं, \"cookies.txt चुनें\" बटन पर क्लिक करें, और इस फ़ाइल को एप्लिकेशन से लिंक करें।",
    
    supportTitle: "संपर्क और समर्थन", supportDesc: "Ridm पूरी तरह से मुफ्त और ओपन-सोर्स है। आप प्रोजेक्ट का समर्थन करने के लिए दान कर सकते हैं और नीचे दिए गए ईमेल पते पर संपर्क कर सकते हैं।", quote: "उदार व्यक्ति का भोजन दवा है, और कंजूस का भोजन बीमारी है।", donateBtn: "दान करें", copied: "कॉपी किया गया!", copy: "कॉपी",
    
    exitTitle: "बाहर जाएं", exitGraceful: "लंबित समाप्त करें", exitForce: "बलपूर्वक बाहर जाएं", errNoInternet: "इंटरनेट नहीं है।", errLocation: "फ़ोल्डर चुनें।", errDuplicate: "लिंक मौजूद है।", errServer: "सर्वर त्रुटि।"
  },
  ES: {
    inputPlaceholder: "Pegue los enlaces...", analyzeBtn: "Analizar", activeTab: "ACTIVO", finishedTab: "FINALIZADO", logsTab: "REGISTROS", pauseAll: "Pausar todo", resumeAll: "Reanudar todo", analyzingMsg: "Analizando...", optionsLoaded: "Opciones cargadas", error: "Error", warning: "Aviso", unknown: "Desconocido", skipped: "OMITIDO", formatSelect: "Seleccionar formato", subSelect: "Subtítulos", tabSelect: "Pestaña", contentCount: "Total :", rangeSelect: "Rango :", downloadAll: "Descargar todo", cancel: "Cancelar", addToQueue: "Añadir a la cola", queued: "Esperando...", downloading: "Descargando...", paused: "Pausado", completed: "Completado", open: "Abrir", share: "Compartir", showInFolder: "Mostrar en carpeta", settingsTitle: "Ajustes", downloadLoc: "UBICACIÓN", locNotSet: "Seleccionar carpeta", locSet: "Carpeta establecida", smartFolder: "Carpetas inteligentes", smartFolderSub: "Ordena archivos por tipo.", autoUpdateEngine: "Actualizar motor automáticamente", autoUpdateEngineSub: "Descarga e instala nuevas versiones sin preguntar.", maxConcurrent: "DESCARGAS MÁX", subPref: "ORDEN DE SUBTÍTULOS", lang1: "Idioma 1", lang2: "Idioma 2", lang3: "Idioma 3", auth: "AUTENTICACIÓN", cookiesNotSet: "Seleccionar cookies.txt", cookiesSet: "Añadido", darkTheme: "Tema oscuro", lightTheme: "Tema claro", sortTitle: "Opciones", sortOptions: "ORDENAR", sortNewOld: "Más recientes", sortAZ: "Por Nombre", sortSize: "Por tamaño", actions: "ACCIONES", clearTab: "Limpiar pestaña", close: "Cerrar", helpTitle: "Ayuda", emptyTab: "No hay registros.", selectLanguage: "Idioma", noSub: "Sin subtítulos", autoSeq: "Secuencia Auto", onlyFirst: "Solo", bestVideo: "Mejor calidad", ifNotAvail: "(Omitir si no está disp.)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• Uso básico:", helpBasicDesc: "Además de ser un gestor de descargas básico, la aplicación puede descargar contenido multimedia de plataformas como YouTube e Instagram, de forma individual o masiva. Si eliges Ridm en el menú para compartir al compartir un vídeo en la app de YouTube, el enlace se analiza automáticamente y queda listo para descargar. Puedes añadir hasta 10 enlaces a la vez, separados por Intro. En las tarjetas de descarga de listas de reproducción y canales, elegir la mejor calidad significa descargar la mayor resolución y calidad disponibles en el servidor de origen. Elegir 2160p o 1080p significa que, durante una descarga masiva, cualquier archivo no disponible en esa resolución se omitirá en lugar de descargarse. Tanto los archivos de vídeo como de audio se pueden descargar con subtítulos/letras incrustados.", helpBasicWarn: "Debe seleccionar una carpeta de descarga en la Configuración para poder descargar.\n\nPara que el proceso de descarga continúe ininterrumpidamente en segundo plano, el uso de la batería de la aplicación debe estar configurado como 'Sin restricciones' en las opciones de energía de Android.",
    helpSmartTitle: "• Carpetas inteligentes:", helpSmartDesc: "Clasifica automáticamente las descargas.",
    helpSubTitle: "• Orden de Subtítulos:", helpSubDesc: "El sistema buscará e incrustará subtítulos automáticamente.",
    helpCookiesTitle: "• Autenticación:", helpCookiesDesc: "Para descargar contenido de Instagram o YouTube con restricción de edad, debe vincular su cuenta:\n1. Instale una extensión \"cookies.txt\" (Chrome, Firefox ADD-ONS, etc.) desde la tienda de extensiones de su navegador en su PC o teléfono.\n2. Inicie sesión en YouTube o Instagram desde el navegador.\n3. Haga clic en el ícono de la extensión y use la opción Download para guardar el archivo cookies.txt en cualquier ubicación de su teléfono.\n4. Vaya a la Configuración de la aplicación, haga clic en el botón \"Seleccionar cookies.txt\" y vincule este archivo.",
    
    supportTitle: "Contacto y Soporte", supportDesc: "Ridm es completamente gratuito y de código abierto. Puede donar para apoyar el proyecto y contactarnos a través del correo electrónico a continuación.", quote: "La comida del generoso es medicina, la comida del avaro es enfermedad.", donateBtn: "Donar", copied: "¡Copiado!", copy: "Copiar",
    
    exitTitle: "Salir", exitGraceful: "Terminar y salir", exitForce: "Forzar salida", errNoInternet: "Sin internet.", errLocation: "Seleccione una carpeta.", errDuplicate: "El enlace existe.", errServer: "Error del servidor."
  },
  FR: {
    inputPlaceholder: "Collez les liens...", analyzeBtn: "Analyser", activeTab: "ACTIF", finishedTab: "TERMINÉ", logsTab: "JOURNAUX", pauseAll: "Tout en pause", resumeAll: "Tout reprendre", analyzingMsg: "Analyse...", optionsLoaded: "Options chargées", error: "Erreur", warning: "Attention", unknown: "Inconnu", skipped: "IGNORÉ", formatSelect: "Format", subSelect: "Sous-titres", tabSelect: "Onglet", contentCount: "Total :", rangeSelect: "Plage :", downloadAll: "Tout télécharger", cancel: "Annuler", addToQueue: "Ajouter à la file", queued: "En attente...", downloading: "Téléchargement...", paused: "En pause", completed: "Terminé", open: "Ouvrir", share: "Partager", showInFolder: "Afficher le dossier", settingsTitle: "Paramètres", downloadLoc: "EMPLACEMENT", locNotSet: "Sélectionner un dossier", locSet: "Dossier défini", smartFolder: "Dossiers intelligents", smartFolderSub: "Trie les fichiers par type.", autoUpdateEngine: "Mise à jour auto. du moteur", autoUpdateEngineSub: "Télécharge et installe les nouvelles versions sans demander.", maxConcurrent: "TÉLÉCHARGEMENTS MÁX", subPref: "ORDRE DES SOUS-TITRES", lang1: "Langue 1", lang2: "Langue 2", lang3: "Langue 3", auth: "AUTHENTIFICATION", cookiesNotSet: "Sélectionner cookies.txt", cookiesSet: "Ajouté", darkTheme: "Thème Sombre", lightTheme: "Thème Clair", sortTitle: "Options", sortOptions: "TRI", sortNewOld: "Plus récents", sortAZ: "Par Nom", sortSize: "Par taille", actions: "ACTIONS", clearTab: "Effacer l'onglet", close: "Fermer", helpTitle: "Aide", emptyTab: "Aucun enregistrement.", selectLanguage: "Langue", noSub: "Pas de sous-titres", autoSeq: "Séquence auto", onlyFirst: "Seulement", bestVideo: "Meilleure qualité", ifNotAvail: "(Ignorer si indisponible)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• Utilisation basique:", helpBasicDesc: "En plus d'être un gestionnaire de téléchargement de base, l'application peut télécharger des contenus multimédias depuis des plateformes comme YouTube et Instagram, individuellement ou en masse. Si vous choisissez Ridm dans le menu de partage lors du partage d'une vidéo dans l'application YouTube, le lien est analysé automatiquement et devient prêt à être téléchargé. Vous pouvez ajouter jusqu'à 10 liens à la fois, séparés par Entrée. Dans les cartes de téléchargement de playlists et de chaînes, choisir la meilleure qualité signifie télécharger la résolution et la qualité les plus élevées disponibles sur le serveur source. Choisir 2160p ou 1080p signifie que, lors d'un téléchargement en masse, tout fichier indisponible dans cette résolution sera ignoré plutôt que téléchargé. Les fichiers vidéo comme audio peuvent être téléchargés avec des sous-titres/paroles intégrés.", helpBasicWarn: "Vous devez sélectionner un dossier de téléchargement dans les Paramètres pour pouvoir télécharger.\n\nPour que le processus de téléchargement se poursuive sans interruption en arrière-plan, l'utilisation de la batterie de l'application doit être définie sur « Non restreint » dans les options d'alimentation Android.",
    helpSmartTitle: "• Dossiers intelligents:", helpSmartDesc: "Trie automatiquement les téléchargements.",
    helpSubTitle: "• Préférence de sous-titres:", helpSubDesc: "Intégrera automatiquement les sous-titres favoris.",
    helpCookiesTitle: "• Authentification:", helpCookiesDesc: "Pour télécharger du contenu Instagram ou YouTube soumis à une limite d'âge, vous devez lier votre compte:\n1. Installez une extension \"cookies.txt\" (Chrome, Firefox ADD-ONS, etc.) depuis la boutique d'extensions de votre navigateur sur votre PC ou téléphone.\n2. Connectez-vous à YouTube ou Instagram depuis le navigateur.\n3. Cliquez sur l'icône de l'extension et utilisez l'option Download pour enregistrer le fichier cookies.txt n'importe où sur votre téléphone.\n4. Allez dans les paramètres de l'application, cliquez sur le bouton \"Sélectionner cookies.txt\" et liez ce fichier.",
    
    supportTitle: "Contact et Soutien", supportDesc: "Ridm est entièrement gratuit et open source. Vous pouvez faire un don pour soutenir le projet et nous contacter via l'adresse e-mail ci-dessous.", quote: "La nourriture de l'homme généreux est un remède, celle de l'avare est une maladie.", donateBtn: "Faire un don", copied: "Copié !", copy: "Copier",
    
    exitTitle: "Quitter", exitGraceful: "Terminer et quitter", exitForce: "Forcer l'arrêt", errNoInternet: "Pas d'internet.", errLocation: "Sélectionnez un dossier.", errDuplicate: "Le lien existe.", errServer: "Erreur serveur."
  },
  BN: {
    inputPlaceholder: "লিঙ্ক পেস্ট করুন...", analyzeBtn: "বিশ্লেষণ", activeTab: "সক্রিয়", finishedTab: "সম্পন্ন", logsTab: "লগ", pauseAll: "পজ করুন", resumeAll: "চালু করুন", analyzingMsg: "বিশ্লেষণ...", optionsLoaded: "লোড হয়েছে", error: "ত্রুটি", warning: "সতর্কতা", unknown: "অজানা", skipped: "বাদ দেওয়া হয়েছে", formatSelect: "ফরম্যাট", subSelect: "সাবটাইটেল", tabSelect: "ট্যাব", contentCount: "মোট :", rangeSelect: "রেঞ্জ :", downloadAll: "সব ডাউনলোড", cancel: "বাতিল", addToQueue: "সারিতে যোগ করুন", queued: "অপেক্ষারত...", downloading: "ডাউনলোড...", paused: "স্থগিত", completed: "সম্পন্ন", open: "খুলুন", share: "শেয়ার", showInFolder: "ফোল্ডার", settingsTitle: "সেটিংস", downloadLoc: "স্থান", locNotSet: "ফোল্ডার নির্বাচন", locSet: "সেট করা হয়েছে", smartFolder: "স্মার্ট ফোল্ডার", smartFolderSub: "ফাইলের ধরন অনুযায়ী সাজান।", autoUpdateEngine: "ইঞ্জিন স্বয়ংক্রিয় আপডেট", autoUpdateEngineSub: "নতুন সংস্করণ পেলে না জিজ্ঞাসা করেই ডাউনলোড ও ইনস্টল করে।", maxConcurrent: "সর্বোচ্চ ডাউনলোড", subPref: "সাবটাইটেল পছন্দ", lang1: "ভাষা ১", lang2: "ভাষা ২", lang3: "ভাষা ৩", auth: "প্রমাণীকরণ", cookiesNotSet: "cookies.txt নির্বাচন", cookiesSet: "যোগ করা হয়েছে", darkTheme: "ডার্ক থিম", lightTheme: "লাইট থিম", sortTitle: "বিকল্প", sortOptions: "সাজানো", sortNewOld: "নতুন থেকে পুরানো", sortAZ: "নাম অনুযায়ী", sortSize: "আকার অনুযায়ী", actions: "ক্রিয়া", clearTab: "মুছুন", close: "বন্ধ", helpTitle: "সাহায্য", emptyTab: "কোনো রেকর্ড নেই।", selectLanguage: "ভাষা", noSub: "কোনো সাবটাইটেল নেই", autoSeq: "স্বয়ংক্রিয় ক্রম", onlyFirst: "শুধুমাত্র", bestVideo: "সেরা মান", ifNotAvail: "(পাওয়া না গেলে এড়িয়ে যান)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• মৌলিক ব্যবহার:", helpBasicDesc: "একটি মৌলিক ডাউনলোড ম্যানেজার হওয়ার পাশাপাশি, অ্যাপটি YouTube, Instagram-এর মতো প্ল্যাটফর্ম থেকে মিডিয়া একক বা বাল্ক আকারে ডাউনলোড করতে পারে। YouTube অ্যাপে কোনো ভিডিও শেয়ার করার সময় শেয়ার তালিকা থেকে Ridm নির্বাচন করলে, লিংকটি স্বয়ংক্রিয়ভাবে বিশ্লেষণ করে ডাউনলোডের জন্য প্রস্তুত হয়ে যায়। আপনি একবারে Enter দ্বারা পৃথক করা সর্বোচ্চ ১০টি লিংক যোগ করতে পারেন। প্লেলিস্ট ও চ্যানেল ডাউনলোড কার্ডে সেরা মান নির্বাচন করার অর্থ হলো উৎস সার্ভারে উপলব্ধ সর্বোচ্চ রেজোলিউশন ও মানের ভিডিও ডাউনলোড করা। 2160p বা 1080p নির্বাচন করার অর্থ হলো, বাল্ক ডাউনলোডের সময় নির্বাচিত রেজোলিউশনে ভিডিও না থাকলে সেই ফাইলটি বাদ দিয়ে পরেরটিতে যাওয়া। ভিডিও ও অডিও উভয় ফাইলই এমবেডেড সাবটাইটেল/লিরিক্স সহ ডাউনলোড করা যায়।", helpBasicWarn: "ডাউনলোড করতে সক্ষম হতে আপনাকে অবশ্যই সেটিংস থেকে একটি ডাউনলোড ফোল্ডার নির্বাচন করতে হবে।\n\nব্যাকগ্রাউন্ডে ডাউনলোড প্রক্রিয়া নিরবচ্ছিন্নভাবে চালিয়ে যাওয়ার জন্য, অ্যাপের ব্যাটারি ব্যবহার অ্যান্ড্রয়েড পাওয়ার বিকল্পগুলিতে 'সীমাবদ্ধ নয়' (Unrestricted) এ সেট করতে হবে।",
    helpSmartTitle: "• স্মার্ট ফোল্ডার:", helpSmartDesc: "ধরন অনুযায়ী স্বয়ংক্রিয়ভাবে সাজায়।",
    helpSubTitle: "• সাবটাইটেল পছন্দ:", helpSubDesc: "স্বয়ংক্রিয়ভাবে সাবটাইটেল খুঁজে যুক্ত করবে।",
    helpCookiesTitle: "• প্রমাণীকরণ:", helpCookiesDesc: "Instagram বা বয়স-সীমাবদ্ধ YouTube কন্টেন্ট ডাউনলোড করতে, আপনাকে অবশ্যই আপনার অ্যাকাউন্ট লিঙ্ক করতে হবে:\n1. আপনার পিসি বা ফোনে আপনার ব্রাউজারের এক্সটেনশন স্টোর (Chrome, Firefox ADD-ONS, ইত্যাদি) থেকে একটি \"cookies.txt\" এক্সটেনশন ইনস্টল করুন।\n2. ব্রাউজার থেকে YouTube বা Instagram-এ লগ ইন করুন।\n3. এক্সটেনশন আইকনে ক্লিক করুন এবং আপনার ফোনে যেকোনো স্থানে cookies.txt ফাইলটি সংরক্ষণ করতে Download বিকল্পটি ব্যবহার করুন।\n4. অ্যাপ সেটিংসে যান, \"cookies.txt নির্বাচন করুন\" বোতামে ক্লিক করুন এবং এই ফাইলটি অ্যাপ্লিকেশনের সাথে লিঙ্ক করুন।",
    
    supportTitle: "যোগাযোগ এবং সমর্থন", supportDesc: "Ridm সম্পূর্ণ বিনামূল্যে এবং ওপেন সোর্স। আপনি প্রকল্পটিকে সমর্থন করার জন্য অনুদান দিতে পারেন এবং নিচের ইমেলের মাধ্যমে যোগাযোগ করতে পারেন।", quote: "উদার ব্যক্তির খাবার হলো ওষুধ, আর কৃপণের খাবার হলো রোগ।", donateBtn: "দান করুন", copied: "কপি করা হয়েছে!", copy: "কপি করুন",
    
    exitTitle: "প্রস্থান", exitGraceful: "শেষ করে প্রস্থান", exitForce: "জোরপূর্বক প্রস্থান", errNoInternet: "ইন্টারনেট নেই।", errLocation: "ফোল্ডার নির্বাচন করুন।", errDuplicate: "লিঙ্কটি বিদ্যমান।", errServer: "সার্ভার ত্রুটি।"
  },
  RU: {
    inputPlaceholder: "Вставьте ссылки...", analyzeBtn: "Анализ", activeTab: "АКТИВНЫЕ", finishedTab: "ЗАВЕРШЕННЫЕ", logsTab: "ЖУРНАЛЫ", pauseAll: "Пауза", resumeAll: "Возобновить", analyzingMsg: "Анализ...", optionsLoaded: "Параметры загружены", error: "Ошибка", warning: "Предупреждение", unknown: "Неизвестно", skipped: "ПРОПУЩЕНО", formatSelect: "Формат", subSelect: "Субтитры", tabSelect: "Вкладка", contentCount: "Всего :", rangeSelect: "Диапазон :", downloadAll: "Скачать все", cancel: "Отмена", addToQueue: "В очередь", queued: "В очереди...", downloading: "Загрузка...", paused: "На паузе", completed: "Завершено", open: "Открыть", share: "Поделиться", showInFolder: "В папке", settingsTitle: "Настройки", downloadLoc: "ПАПКА", locNotSet: "Выберите папку", locSet: "Папка установлена", smartFolder: "Умные папки", smartFolderSub: "Авто-сортировка.", autoUpdateEngine: "Автообновление движка", autoUpdateEngineSub: "Скачивает и устанавливает новые версии без вопросов.", maxConcurrent: "ОДНОВРЕМЕННЫЕ", subPref: "ПРИОРИТЕТ СУБТИТРОВ", lang1: "Язык 1", lang2: "Язык 2", lang3: "Язык 3", auth: "АВТОРИЗАЦИЯ", cookiesNotSet: "Выбрать cookies.txt", cookiesSet: "Добавлен", darkTheme: "Тёмная тема", lightTheme: "Светлая тема", sortTitle: "Опции", sortOptions: "СОРТИРОВКА", sortNewOld: "Сначала новые", sortAZ: "По имени", sortSize: "По размеру", actions: "ДЕЙСТВИЯ", clearTab: "Очистить вкладку", close: "Закрыть", helpTitle: "Справка", emptyTab: "Нет записей.", selectLanguage: "Язык", noSub: "Без субтитров", autoSeq: "Автопоследовательность", onlyFirst: "Только", bestVideo: "Лучшее качество", ifNotAvail: "(Пропустить, если нет)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• Использование:", helpBasicDesc: "Помимо базового менеджера загрузок, приложение умеет скачивать медиа с таких платформ, как YouTube и Instagram, по отдельности или массово. Если при отправке видео в приложении YouTube выбрать Ridm из списка общего доступа, ссылка будет автоматически проанализирована и подготовлена к загрузке. За один раз можно добавить до 10 ссылок, разделённых клавишей Enter. В карточках загрузки плейлистов и каналов выбор наилучшего качества означает загрузку видео с максимальным доступным на исходном сервере разрешением и качеством. Выбор 2160p или 1080p означает, что при массовой загрузке файлы, недоступные в этом разрешении, будут пропущены, а загрузка продолжится со следующего. И видео, и аудиофайлы можно скачивать со встроенными субтитрами/текстом песни.", helpBasicWarn: "Для загрузки необходимо выбрать папку загрузки в Настройках.\n\nЧтобы процесс загрузки продолжался непрерывно в фоновом режиме, использование батареи приложения должно быть установлено на «Без ограничений» в параметрах питания Android.",
    helpSmartTitle: "• Умные папки:", helpSmartDesc: "Автоматически сортирует загрузки.",
    helpSubTitle: "• Приоритет субтитров:", helpSubDesc: "Система автоматически найдет и встроит субтитры.",
    helpCookiesTitle: "• Авторизация:", helpCookiesDesc: "Чтобы скачивать контент из Instagram или YouTube с возрастными ограничениями, необходимо привязать свой аккаунт:\n1. Установите расширение \"cookies.txt\" (Chrome, Firefox ADD-ONS и т. д.) из магазина расширений вашего браузера на ПК или телефоне.\n2. Войдите в YouTube или Instagram через браузер.\n3. Нажмите на значок расширения и используйте опцию Download, чтобы сохранить файл cookies.txt в любом месте на вашем телефоне.\n4. Перейдите в настройки приложения, нажмите кнопку \"Выбрать cookies.txt\" и привяжите этот файл к приложению.",
    
    supportTitle: "Связь и поддержка", supportDesc: "Ridm полностью бесплатен и имеет открытый исходный код. Вы можете сделать пожертвование на развитие проекта и связаться с нами по почте.", quote: "Пища щедрого — лекарство, пища скупого — болезнь.", donateBtn: "Пожертвовать", copied: "Скопировано!", copy: "Копировать",
    
    exitTitle: "Выход", exitGraceful: "Завершить и выйти", exitForce: "Принудительный выход", errNoInternet: "Нет интернета.", errLocation: "Выберите папку.", errDuplicate: "Ссылка существует.", errServer: "Ошибка сервера."
  }
};