export const DICTIONARY = {
  TR: {
    inputPlaceholder: "Linkleri buraya yapıştırın (Max 10 satır)...", analyzeBtn: "Analiz Et", activeTab: "AKTİF", finishedTab: "BİTENLER", logsTab: "LOGLAR", pauseAll: "Tümünü Duraklat", resumeAll: "Tümünü Devam Ettir", analyzingMsg: "Bağlantı inceleniyor...", optionsLoaded: "Medya Seçenekleri Yüklendi", error: "Hata", warning: "Uyarı", unknown: "Bilinmiyor", skipped: "ATLANDI", formatSelect: "Format Seçiniz", subSelect: "Altyazı Tercihi", tabSelect: "Sekme Seçiniz", contentCount: "Toplam içerik sayısı :", rangeSelect: "Aralık seç :", downloadAll: "Hepsini indir", cancel: "İptal", addToQueue: "Kuyruğa Ekle", queued: "Kuyrukta bekliyor...", downloading: "İndiriliyor...", paused: "Duraklatıldı", completed: "Tamamlandı", open: "Aç", share: "Paylaş / Kopyala", showInFolder: "Klasörde Göster", settingsTitle: "Ayarlar", downloadLoc: "İNDİRME KONUMU", locNotSet: "Klasör Seçiniz (Zorunlu)", locSet: "Klasör Konumu Ayarlandı", smartFolder: "Akıllı Klasörleme", smartFolderSub: "Dosyaları türlerine göre alt klasörlere ayırır.", maxConcurrent: "MAKS. İNDİRME", subPref: "ALTYAZI TERCİH SIRASI", lang1: "1. Dil", lang2: "2. Dil", lang3: "3. Dil", auth: "KİMLİK DOĞRULAMA", cookiesNotSet: "cookies.txt Seçiniz", cookiesSet: "cookies.txt Eklendi", darkTheme: "Karanlık Tema Aktif", lightTheme: "Aydınlık Tema", sortTitle: "Seçenekler", sortOptions: "SIRALAMA", sortNewOld: "Yeniden Eskiye", sortAZ: "İsme Göre (A-Z)", sortSize: "Boyuta Göre", actions: "İŞLEMLER", clearTab: "Geçerli Sekmeyi Temizle", close: "Kapat", helpTitle: "Yardım Konuları", emptyTab: "Bu sekmede gösterilecek kayıt yok.", selectLanguage: "Dil Seçiniz", noSub: "Altyazı İndirme", autoSeq: "Oto Sıralı - Varsa", onlyFirst: "Sadece", bestVideo: "En İyi Kalite", ifNotAvail: "(Yoksa atlanır)", audioOnly: "(Sadece ses)", audioSub: "(Ses + Altyazı)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• Temel Kullanım:", helpBasicDesc: "Uygulama temel bir indirme yöneticisinin yanı sıra Youtube, Instagram gibi media içeriklerini tek tek yada toplu indirme yeteneklerine sahiptir. Youtube uygulamasında herhangi bir videoyu paylaş dediğinizde çıkan uygulama listesinden Ridm seçerseniz, otomatik olarak link analiz edilerek indirmeye hazır hale gelebilmektedir. Uygulama içerisinde tek seferde enter ile ayrılmış max 10 link ekleyebilirsiniz. İndirme yapabilmek için Ayarlar menüsünden indirmelerin kaydedileceği klasörü seçmeniz gerekmektedir. Playlist ve Kanal indirme kartlarında bulunan format seçiminde en iyi kaliteyi seçtiğinizde kaynak sunucudaki en yüksek çözünürlük ve kalitedeki videoları indir anlamına gelir. 2160p ve 1080p formatlarından birini seçtiğinizde toplu indirme esnasında seçili çözünürlükte video yoksa o dosyayı indirmeyip sıradakine geç anlamına gelir. Mp3, M4A ve Opus sadece ses dosyalarını indirirken, Altyazılı ses dosyası indirmek istediğinizde M4A formatını seçmeniz gerekmektedir.", helpBasicWarn: "İndirme işleminin arka planda kesintisiz devam edebilmesi için uygulamanın Android güç seçeneklerinde pil kullanımının kısıtlama yok olarak ayarlanması gerekmektedir.",
    helpSmartTitle: "• Akıllı Klasörleme:", helpSmartDesc: "Aktif edildiğinde indirmeleriniz türlerine göre (Videos, Audio vb.) otomatik olarak alt klasörlere ayrılır.",
    helpSubTitle: "• Altyazı Tercihi (Toplu İndirmeler):", helpSubDesc: "Ayarlar menüsündeki 'Altyazı Tercih Sırası', Kanal ve Playlist gibi toplu indirmelerde her video için size tek tek altyazı sorma zahmetinden kurtarır. İndirme ekranında 'Oto Sıralı' seçeneğini işaretlerseniz; sistem her videoda 1. dile bakar, bulamazsa 2. dile geçer ve bulduğunu gömer. 'Sadece' seçeneği ise yalnızca belirttiğiniz 1. dil videoda mevcutsa indirir.",
    helpCookiesTitle: "• Cookies / Kimlik Doğrulama:", helpCookiesDesc: "Instagram veya yaş kısıtlamalı YouTube içeriklerini indirebilmek için hesabınızı uygulamaya tanıtmanız gerekir:\n1. Bilgisayarınızdaki tarayıcıya (Chrome vb.) \"Get cookies.txt LOCALLY\" eklentisini kurun.\n2. Tarayıcıdan YouTube veya Instagram'a girip oturum açın.\n3. Eklenti simgesine tıklayıp 'Export' butonu ile çerezleri \".txt\" dosyası olarak bilgisayarınıza indirin.\n4. Bu dosyayı telefonunuza gönderin.\n5. Uygulama Ayarlarından \"Cookies Seçiniz\" butonuna tıklayıp bu dosyayı uygulamaya bağlayın.",
    
    supportTitle: "İletişim & Destek", supportDesc: "Ridm tamamen ücretsiz ve açık kaynaklıdır. Projeye destek olmak için bağış yapabilir, iletişim için aşağıdaki mail adresinden ulaşabilirsiniz.", quote: "Cömertin yemeği şifadır, cimrinin yemeği hastalıktır.", donateBtn: "Destek Ol", copied: "Kopyalandı!", copy: "Kopyala",
    
    exitTitle: "Çıkış Yap", exitGraceful: "Yarım kalanları bitir ve çık", exitForce: "Zorla çıkış yap", errNoInternet: "İnternet bağlantınız yok.", errLocation: "Lütfen önce Ayarlar menüsünden indirme klasörü seçiniz.", errDuplicate: "Bu link mevcut oturumda var.", errServer: "Sunucu yanıt vermedi."
  },
  EN: {
    inputPlaceholder: "Paste links here (Max 10 lines)...", analyzeBtn: "Analyze", activeTab: "ACTIVE", finishedTab: "FINISHED", logsTab: "LOGS", pauseAll: "Pause All", resumeAll: "Resume All", analyzingMsg: "Analyzing...", optionsLoaded: "Media Options Loaded", error: "Error", warning: "Warning", unknown: "Unknown", skipped: "SKIPPED", formatSelect: "Select Format", subSelect: "Subtitle Preference", tabSelect: "Select Tab", contentCount: "Total content count :", rangeSelect: "Select range :", downloadAll: "Download all", cancel: "Cancel", addToQueue: "Add to Queue", queued: "Waiting in queue...", downloading: "Downloading...", paused: "Paused", completed: "Completed", open: "Open", share: "Share / Copy", showInFolder: "Show in Folder", settingsTitle: "Settings", downloadLoc: "DOWNLOAD LOCATION", locNotSet: "Select Folder", locSet: "Folder Location Set", smartFolder: "Smart Folders", smartFolderSub: "Automatically sort files into subfolders.", maxConcurrent: "MAX DOWNLOADS", subPref: "SUBTITLE ORDER", lang1: "1st Lang", lang2: "2nd Lang", lang3: "3rd Lang", auth: "AUTHENTICATION", cookiesNotSet: "Select cookies.txt", cookiesSet: "cookies.txt Added", darkTheme: "Dark Theme", lightTheme: "Light Theme", sortTitle: "Options", sortOptions: "SORTING", sortNewOld: "Newest to Oldest", sortAZ: "By Name (A-Z)", sortSize: "By Size", actions: "ACTIONS", clearTab: "Clear Current Tab", close: "Close", helpTitle: "Help Topics", emptyTab: "No records to display.", selectLanguage: "Select Language", noSub: "No Subtitles", autoSeq: "Auto Sequence", onlyFirst: "Only", bestVideo: "Best Quality", ifNotAvail: "(Skip if unavailable)", audioOnly: "(Audio only)", audioSub: "(Audio + Sub)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• Basic Usage:", helpBasicDesc: "The app has the capability to download media content individually or in bulk from sites like YouTube and Instagram, as well as a basic download manager. If you tap share on any video in the YouTube app and select Ridm, the link is automatically analyzed and ready for download. You can add up to 10 links at once separated by enter. You must select a download folder from Settings. Selecting 'Best Quality' in Playlist/Channel downloads fetches the highest resolution video available on the source server. If you select 2160p or 1080p and that resolution is missing during bulk download, it skips that file and moves to the next. MP3, M4A, and Opus only download audio files; you must select M4A if you want to download an audio file with subtitles.", helpBasicWarn: "In order for the download process to continue uninterrupted in the background, the app's battery usage must be set to 'Unrestricted' in Android power options.",
    helpSmartTitle: "• Smart Folders:", helpSmartDesc: "When activated, downloads are sorted into subfolders by type.",
    helpSubTitle: "• Subtitle Preference:", helpSubDesc: "The system checks for the 1st language, then the 2nd, and embeds the first one it finds automatically.",
    helpCookiesTitle: "• Cookies / Authentication:", helpCookiesDesc: "To download Instagram or age-restricted YouTube content, you must link your account:\n1. Install 'Get cookies.txt LOCALLY' extension on your desktop browser.\n2. Log in to YouTube or Instagram.\n3. Export cookies as a '.txt' file.\n4. Send this file to your phone.\n5. Link it via 'Select Cookies' in App Settings.",
    
    supportTitle: "Contact & Support", supportDesc: "Ridm is completely free and open-source. You can donate to support the project and contact us via the email address below.", quote: "The generous' food heals, the miser's food sickens.", donateBtn: "Donate", copied: "Copied!", copy: "Copy",
    
    exitTitle: "Exit", exitGraceful: "Finish pending and exit", exitForce: "Force Exit", errNoInternet: "No internet connection.", errLocation: "Please select a download folder first.", errDuplicate: "Link already exists.", errServer: "Server error."
  },
  AR: {
    inputPlaceholder: "الصق الروابط هنا...", analyzeBtn: "تحليل", activeTab: "نشط", finishedTab: "مكتمل", logsTab: "سجلات", pauseAll: "إيقاف الكل", resumeAll: "استئناف الكل", analyzingMsg: "جارٍ التحليل...", optionsLoaded: "تم التحميل", error: "خطأ", warning: "تحذير", unknown: "مجهول", skipped: "تم التخطي", formatSelect: "اختر التنسيق", subSelect: "الترجمة", tabSelect: "التبويب", contentCount: "إجمالي المحتوى :", rangeSelect: "النطاق :", downloadAll: "تنزيل الكل", cancel: "إلغاء", addToQueue: "طابور", queued: "في الانتظار...", downloading: "تنزيل...", paused: "موقوف", completed: "مكتمل", open: "فتح", share: "مشاركة", showInFolder: "في المجلد", settingsTitle: "إعدادات", downloadLoc: "موقع التنزيل", locNotSet: "حدد مجلد", locSet: "تم التعيين", smartFolder: "مجلدات ذكية", smartFolderSub: "فرز تلقائي.", maxConcurrent: "الحد الأقصى", subPref: "ترتيب الترجمة", lang1: "لغة 1", lang2: "لغة 2", lang3: "لغة 3", auth: "المصادقة", cookiesNotSet: "حدد cookies.txt", cookiesSet: "تمت الإضافة", darkTheme: "مظهر داكن", lightTheme: "مظهر فاتح", sortTitle: "خيارات", sortOptions: "فرز", sortNewOld: "الأحدث", sortAZ: "حسب الاسم", sortSize: "حسب الحجم", actions: "إجراءات", clearTab: "مسح السجل", close: "إغلاق", helpTitle: "المساعدة", emptyTab: "لا يوجد محتوى.", selectLanguage: "اختر اللغة", noSub: "بدون ترجمة", autoSeq: "تسلسل تلقائي", onlyFirst: "فقط", bestVideo: "أفضل جودة", ifNotAvail: "(تخطي إذا غير متوفر)", audioOnly: "(صوت فقط)", audioSub: "(صوت + ترجمة)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• الاستخدام الأساسي:", helpBasicDesc: "يحتوي التطبيق على مدير تنزيل أساسي بالإضافة إلى القدرة على تنزيل محتوى الوسائط من مواقع مثل YouTube و Instagram. إذا اخترت مشاركة فيديو في تطبيق YouTube وحددت Ridm، فسيتم تحليل الرابط تلقائيًا. يمكنك إضافة حتى 10 روابط دفعة واحدة. يجب تحديد مجلد للتنزيل من الإعدادات. اختيار 'أفضل جودة' يعني تنزيل أعلى دقة متاحة. إذا اخترت 2160p أو 1080p ولم تكن الدقة موجودة، فسيتم تخطي الملف. تعتبر صيغ MP3 و M4A و Opus للصوت فقط، ويجب اختيار M4A لتنزيل الصوت مع الترجمة.", helpBasicWarn: "لكي تستمر عملية التنزيل دون انقطاع في الخلفية، يجب ضبط استخدام بطارية التطبيق على 'غير مقيد' في خيارات طاقة Android.",
    helpSmartTitle: "• المجلدات الذكية:", helpSmartDesc: "فرز التنزيلات تلقائياً في مجلدات.",
    helpSubTitle: "• تفضيل الترجمة:", helpSubDesc: "دمج الترجمات تلقائياً حسب اللغات المفضلة.",
    helpCookiesTitle: "• ملفات تعريف الارتباط / المصادقة:", helpCookiesDesc: "لتنزيل محتوى مقيد، يجب ربط حسابك بملف cookies.txt.",
    
    supportTitle: "التواصل والدعم", supportDesc: "تطبيق Ridm مجاني تمامًا ومفتوح المصدر. يمكنك التبرع لدعم المشروع والتواصل عبر عنوان البريد الإلكتروني أدناه.", quote: "طَعَامُ الْجَوَادِ دَوَاءٌ، وَطَعَامُ الْبَخِيلِ دَاءٌ", donateBtn: "ادعمنا", copied: "تم النسخ!", copy: "ينسخ",
    
    exitTitle: "خروج", exitGraceful: "إنهاء المعلق", exitForce: "خروج إجباري", errNoInternet: "لا يوجد إنترنت.", errLocation: "حدد مجلد التنزيل.", errDuplicate: "الرابط موجود.", errServer: "خطأ في الخادم."
  },
  ZH: {
    inputPlaceholder: "在此处粘贴链接...", analyzeBtn: "分析", activeTab: "活跃", finishedTab: "已完成", logsTab: "日志", pauseAll: "全部暂停", resumeAll: "全部恢复", analyzingMsg: "分析中...", optionsLoaded: "选项已加载", error: "错误", warning: "警告", unknown: "未知", skipped: "已跳过", formatSelect: "选择格式", subSelect: "字幕", tabSelect: "标签页", contentCount: "总数 :", rangeSelect: "范围 :", downloadAll: "下载全部", cancel: "取消", addToQueue: "加入队列", queued: "等待中...", downloading: "下载中...", paused: "已暂停", completed: "已完成", open: "打开", share: "分享", showInFolder: "显示文件夹", settingsTitle: "设置", downloadLoc: "下载位置", locNotSet: "选择文件夹", locSet: "位置已设置", smartFolder: "智能文件夹", smartFolderSub: "自动分类文件。", maxConcurrent: "最大下载数", subPref: "字幕顺序", lang1: "第一语言", lang2: "第二语言", lang3: "第三语言", auth: "身份验证", cookiesNotSet: "选择 cookies.txt", cookiesSet: "已添加", darkTheme: "深色主题", lightTheme: "浅色主题", sortTitle: "选项", sortOptions: "排序", sortNewOld: "从新到旧", sortAZ: "按名称", sortSize: "按大小", actions: "操作", clearTab: "清除记录", close: "关闭", helpTitle: "帮助", emptyTab: "无记录。", selectLanguage: "选择语言", noSub: "无字幕", autoSeq: "自动顺序", onlyFirst: "仅", bestVideo: "最佳质量", ifNotAvail: "(如不可用则跳过)", audioOnly: "(仅音频)", audioSub: "(音频+字幕)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• 基本用法：", helpBasicDesc: "该应用包含一个基本下载管理器，并可以单独或批量下载来自 YouTube 和 Instagram 等媒体内容。如果您在 YouTube 中分享视频并选择 Ridm，链接将自动分析。一次最多可添加 10 个链接。您必须从设置中选择下载文件夹。选择“最佳质量”会获取最高分辨率的视频。如果选择 2160p 或 1080p 且该分辨率缺失，则跳过该文件。MP3、M4A 和 Opus 仅为音频格式；要下载带字幕的音频，必须选择 M4A。", helpBasicWarn: "为了使下载过程在后台不间断地继续，必须在 Android 电源选项中将应用程序的电池使用设置为“无限制”。",
    helpSmartTitle: "• 智能文件夹：", helpSmartDesc: "按类型自动分类文件。",
    helpSubTitle: "• 字幕偏好：", helpSubDesc: "自动查找并嵌入首选字幕。",
    helpCookiesTitle: "• 身份验证：", helpCookiesDesc: "使用 cookies.txt 下载受限内容。",
    
    supportTitle: "联系与支持", supportDesc: "Ridm完全免费且开源。您可以捐赠以支持该项目，并通过以下电子邮件地址与我们联系。", quote: "慷慨者的食物是良药，吝啬者的食物是毒药。", donateBtn: "捐赠", copied: "已复制！", copy: "复制",
    
    exitTitle: "退出", exitGraceful: "完成待处理", exitForce: "强制退出", errNoInternet: "无网络。", errLocation: "请选择文件夹。", errDuplicate: "链接已存在。", errServer: "服务器错误。"
  },
  HI: {
    inputPlaceholder: "लिंक पेस्ट करें...", analyzeBtn: "विश्लेषण", activeTab: "सक्रिय", finishedTab: "पूरा", logsTab: "लॉग", pauseAll: "रोकें", resumeAll: "फिर शुरू करें", analyzingMsg: "विश्लेषण हो रहा है...", optionsLoaded: "विकल्प लोड हुए", error: "त्रुटि", warning: "चेतावनी", unknown: "अज्ञात", skipped: "छोड़ दिया", formatSelect: "प्रारूप चुनें", subSelect: "उपशीर्षक", tabSelect: "टैब", contentCount: "कुल :", rangeSelect: "सीमा :", downloadAll: "सभी डाउनलोड करें", cancel: "रद्द करें", addToQueue: "कतार में जोड़ें", queued: "प्रतीक्षा...", downloading: "डाउनलोड...", paused: "रोका गया", completed: "पूरा हुआ", open: "खोलें", share: "साझा करें", showInFolder: "फ़ोल्डर दिखाएं", settingsTitle: "सेटिंग्स", downloadLoc: "स्थान", locNotSet: "फ़ोल्डर चुनें", locSet: "सेट किया गया", smartFolder: "स्मार्ट फोल्डर", smartFolderSub: "स्वतः सॉर्ट करें।", maxConcurrent: "अधिकतम डाउनलोड", subPref: "उपशीर्षक क्रम", lang1: "भाषा 1", lang2: "भाषा 2", lang3: "भाषा 3", auth: "प्रमाणीकरण", cookiesNotSet: "cookies.txt चुनें", cookiesSet: "जोड़ा गया", darkTheme: "डार्क", lightTheme: "लाइट", sortTitle: "विकल्प", sortOptions: "क्रमबद्ध", sortNewOld: "नवीनतम", sortAZ: "नाम से", sortSize: "आकार से", actions: "कार्रवाई", clearTab: "साफ़ करें", close: "बंद करें", helpTitle: "मदद", emptyTab: "कोई रिकॉर्ड नहीं।", selectLanguage: "भाषा चुनें", noSub: "कोई उपशीर्षक नहीं", autoSeq: "ऑटो अनुक्रम", onlyFirst: "केवल", bestVideo: "सर्वश्रेष्ठ", ifNotAvail: "(उपलब्ध न होने पर छोड़ें)", audioOnly: "(केवल ऑडियो)", audioSub: "(ऑडियो + उपशीर्षक)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• मूल उपयोग:", helpBasicDesc: "ऐप में एक बुनियादी डाउनलोड प्रबंधक है और यह YouTube और Instagram जैसी मीडिया सामग्री डाउनलोड कर सकता है। यदि आप YouTube ऐप में किसी भी वीडियो पर शेयर टैप करते हैं और Ridm चुनते हैं, तो लिंक स्वचालित रूप से विश्लेषण हो जाता है। आप एक बार में 10 लिंक तक जोड़ सकते हैं। आपको सेटिंग्स से डाउनलोड फ़ोल्डर चुनना होगा। 'सर्वश्रेष्ठ गुणवत्ता' चुनने पर उच्चतम रिज़ॉल्यूशन वाला वीडियो मिलता है। यदि 2160p या 1080p उपलब्ध नहीं है, तो फ़ाइल छोड़ दी जाती है। उपशीर्षक के साथ ऑडियो के लिए M4A चुनें।", helpBasicWarn: "डाउनलोड प्रक्रिया को पृष्ठभूमि में निर्बाध रूप से जारी रखने के लिए, एंड्रॉइड पावर विकल्पों में ऐप के बैटरी उपयोग को 'अप्रतिबंधित' (Unrestricted) पर सेट किया जाना चाहिए।",
    helpSmartTitle: "• स्मार्ट फ़ोल्डर:", helpSmartDesc: "स्मार्ट फ़ोल्डर स्वतः सॉर्ट करता है।",
    helpSubTitle: "• उपशीर्षक प्राथमिकता:", helpSubDesc: "स्वचालित रूप से उपशीर्षक एम्बेड करेगा।",
    helpCookiesTitle: "• प्रमाणीकरण:", helpCookiesDesc: "प्रतिबंधित सामग्री डाउनलोड करने के लिए अपना खाता लिंक करें (cookies.txt)।",
    
    supportTitle: "संपर्क और समर्थन", supportDesc: "Ridm पूरी तरह से मुफ्त और ओपन-सोर्स है। आप प्रोजेक्ट का समर्थन करने के लिए दान कर सकते हैं और नीचे दिए गए ईमेल पते पर संपर्क कर सकते हैं।", quote: "उदार व्यक्ति का भोजन दवा है, और कंजूस का भोजन बीमारी है।", donateBtn: "दान करें", copied: "कॉपी किया गया!", copy: "कॉपी",
    
    exitTitle: "बाहर जाएं", exitGraceful: "लंबित समाप्त करें", exitForce: "बलपूर्वक बाहर जाएं", errNoInternet: "इंटरनेट नहीं है।", errLocation: "फ़ोल्डर चुनें।", errDuplicate: "लिंक मौजूद है।", errServer: "सर्वर त्रुटि।"
  },
  ES: {
    inputPlaceholder: "Pegue los enlaces...", analyzeBtn: "Analizar", activeTab: "ACTIVO", finishedTab: "FINALIZADO", logsTab: "REGISTROS", pauseAll: "Pausar todo", resumeAll: "Reanudar todo", analyzingMsg: "Analizando...", optionsLoaded: "Opciones cargadas", error: "Error", warning: "Aviso", unknown: "Desconocido", skipped: "OMITIDO", formatSelect: "Seleccionar formato", subSelect: "Subtítulos", tabSelect: "Pestaña", contentCount: "Total :", rangeSelect: "Rango :", downloadAll: "Descargar todo", cancel: "Cancelar", addToQueue: "Añadir a la cola", queued: "Esperando...", downloading: "Descargando...", paused: "Pausado", completed: "Completado", open: "Abrir", share: "Compartir", showInFolder: "Mostrar en carpeta", settingsTitle: "Ajustes", downloadLoc: "UBICACIÓN", locNotSet: "Seleccionar carpeta", locSet: "Carpeta establecida", smartFolder: "Carpetas inteligentes", smartFolderSub: "Ordena archivos por tipo.", maxConcurrent: "DESCARGAS MÁX", subPref: "ORDEN DE SUBTÍTULOS", lang1: "Idioma 1", lang2: "Idioma 2", lang3: "Idioma 3", auth: "AUTENTICACIÓN", cookiesNotSet: "Seleccionar cookies.txt", cookiesSet: "Añadido", darkTheme: "Tema oscuro", lightTheme: "Tema claro", sortTitle: "Opciones", sortOptions: "ORDENAR", sortNewOld: "Más recientes", sortAZ: "Por Nombre", sortSize: "Por tamaño", actions: "ACCIONES", clearTab: "Limpiar pestaña", close: "Cerrar", helpTitle: "Ayuda", emptyTab: "No hay registros.", selectLanguage: "Idioma", noSub: "Sin subtítulos", autoSeq: "Secuencia Auto", onlyFirst: "Solo", bestVideo: "Mejor calidad", ifNotAvail: "(Omitir si no está disp.)", audioOnly: "(Solo audio)", audioSub: "(Audio + Sub)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• Uso básico:", helpBasicDesc: "La aplicación tiene un administrador de descargas básico y puede descargar contenido de YouTube e Instagram. Si toca compartir en la aplicación de YouTube y selecciona Ridm, el enlace se analiza automáticamente. Puede añadir hasta 10 enlaces separados por intro. Debe seleccionar una carpeta en Ajustes. Seleccionar 'Mejor calidad' obtiene el video de mayor resolución. Si selecciona 2160p o 1080p y no está disponible, se omite. Seleccione M4A si desea descargar audio con subtítulos.", helpBasicWarn: "Para que el proceso de descarga continúe ininterrumpidamente en segundo plano, el uso de la batería de la aplicación debe estar configurado como 'Sin restricciones' en las opciones de energía de Android.",
    helpSmartTitle: "• Carpetas inteligentes:", helpSmartDesc: "Clasifica automáticamente las descargas.",
    helpSubTitle: "• Orden de Subtítulos:", helpSubDesc: "El sistema buscará e incrustará subtítulos automáticamente.",
    helpCookiesTitle: "• Autenticación:", helpCookiesDesc: "Utilice cookies.txt para descargar contenido restringido.",
    
    supportTitle: "Contacto y Soporte", supportDesc: "Ridm es completamente gratuito y de código abierto. Puede donar para apoyar el proyecto y contactarnos a través del correo electrónico a continuación.", quote: "La comida del generoso es medicina, la comida del avaro es enfermedad.", donateBtn: "Donar", copied: "¡Copiado!", copy: "Copiar",
    
    exitTitle: "Salir", exitGraceful: "Terminar y salir", exitForce: "Forzar salida", errNoInternet: "Sin internet.", errLocation: "Seleccione una carpeta.", errDuplicate: "El enlace existe.", errServer: "Error del servidor."
  },
  FR: {
    inputPlaceholder: "Collez les liens...", analyzeBtn: "Analyser", activeTab: "ACTIF", finishedTab: "TERMINÉ", logsTab: "JOURNAUX", pauseAll: "Tout en pause", resumeAll: "Tout reprendre", analyzingMsg: "Analyse...", optionsLoaded: "Options chargées", error: "Erreur", warning: "Attention", unknown: "Inconnu", skipped: "IGNORÉ", formatSelect: "Format", subSelect: "Sous-titres", tabSelect: "Onglet", contentCount: "Total :", rangeSelect: "Plage :", downloadAll: "Tout télécharger", cancel: "Annuler", addToQueue: "Ajouter à la file", queued: "En attente...", downloading: "Téléchargement...", paused: "En pause", completed: "Terminé", open: "Ouvrir", share: "Partager", showInFolder: "Afficher le dossier", settingsTitle: "Paramètres", downloadLoc: "EMPLACEMENT", locNotSet: "Sélectionner un dossier", locSet: "Dossier défini", smartFolder: "Dossiers intelligents", smartFolderSub: "Trie les fichiers par type.", maxConcurrent: "TÉLÉCHARGEMENTS MÁX", subPref: "ORDRE DES SOUS-TITRES", lang1: "Langue 1", lang2: "Langue 2", lang3: "Langue 3", auth: "AUTHENTIFICATION", cookiesNotSet: "Sélectionner cookies.txt", cookiesSet: "Ajouté", darkTheme: "Thème Sombre", lightTheme: "Thème Clair", sortTitle: "Options", sortOptions: "TRI", sortNewOld: "Plus récents", sortAZ: "Par Nom", sortSize: "Par taille", actions: "ACTIONS", clearTab: "Effacer l'onglet", close: "Fermer", helpTitle: "Aide", emptyTab: "Aucun enregistrement.", selectLanguage: "Langue", noSub: "Pas de sous-titres", autoSeq: "Séquence auto", onlyFirst: "Seulement", bestVideo: "Meilleure qualité", ifNotAvail: "(Ignorer si indisponible)", audioOnly: "(Audio uniquement)", audioSub: "(Audio + Sous-titres)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• Utilisation basique:", helpBasicDesc: "L'application gère les téléchargements et peut télécharger des médias YouTube et Instagram. Si vous appuyez sur partager sur l'application YouTube et choisissez Ridm, le lien est analysé automatiquement. Vous pouvez ajouter jusqu'à 10 liens. Vous devez choisir un dossier dans les Paramètres. 'Meilleure qualité' télécharge la plus haute résolution. Si 2160p ou 1080p est manquant, le fichier est ignoré. Choisissez M4A pour télécharger de l'audio avec des sous-titres.", helpBasicWarn: "Pour que le processus de téléchargement se poursuive sans interruption en arrière-plan, l'utilisation de la batterie de l'application doit être définie sur « Non restreint » dans les options d'alimentation Android.",
    helpSmartTitle: "• Dossiers intelligents:", helpSmartDesc: "Trie automatiquement les téléchargements.",
    helpSubTitle: "• Préférence de sous-titres:", helpSubDesc: "Intégrera automatiquement les sous-titres favoris.",
    helpCookiesTitle: "• Authentification:", helpCookiesDesc: "Utilisez cookies.txt pour le contenu restreint par âge.",
    
    supportTitle: "Contact et Soutien", supportDesc: "Ridm est entièrement gratuit et open source. Vous pouvez faire un don pour soutenir le projet et nous contacter via l'adresse e-mail ci-dessous.", quote: "La nourriture de l'homme généreux est un remède, celle de l'avare est une maladie.", donateBtn: "Faire un don", copied: "Copié !", copy: "Copier",
    
    exitTitle: "Quitter", exitGraceful: "Terminer et quitter", exitForce: "Forcer l'arrêt", errNoInternet: "Pas d'internet.", errLocation: "Sélectionnez un dossier.", errDuplicate: "Le lien existe.", errServer: "Erreur serveur."
  },
  BN: {
    inputPlaceholder: "লিঙ্ক পেস্ট করুন...", analyzeBtn: "বিশ্লেষণ", activeTab: "সক্রিয়", finishedTab: "সম্পন্ন", logsTab: "লগ", pauseAll: "পজ করুন", resumeAll: "চালু করুন", analyzingMsg: "বিশ্লেষণ...", optionsLoaded: "লোড হয়েছে", error: "ত্রুটি", warning: "সতর্কতা", unknown: "অজানা", skipped: "বাদ দেওয়া হয়েছে", formatSelect: "ফরম্যাট", subSelect: "সাবটাইটেল", tabSelect: "ট্যাব", contentCount: "মোট :", rangeSelect: "রেঞ্জ :", downloadAll: "সব ডাউনলোড", cancel: "বাতিল", addToQueue: "সারিতে যোগ করুন", queued: "অপেক্ষারত...", downloading: "ডাউনলোড...", paused: "স্থগিত", completed: "সম্পন্ন", open: "খুলুন", share: "শেয়ার", showInFolder: "ফোল্ডার", settingsTitle: "সেটিংস", downloadLoc: "স্থান", locNotSet: "ফোল্ডার নির্বাচন", locSet: "সেট করা হয়েছে", smartFolder: "স্মার্ট ফোল্ডার", smartFolderSub: "ফাইলের ধরন অনুযায়ী সাজান।", maxConcurrent: "সর্বোচ্চ ডাউনলোড", subPref: "সাবটাইটেল পছন্দ", lang1: "ভাষা ১", lang2: "ভাষা ২", lang3: "ভাষা ৩", auth: "প্রমাণীকরণ", cookiesNotSet: "cookies.txt নির্বাচন", cookiesSet: "যোগ করা হয়েছে", darkTheme: "ডার্ক থিম", lightTheme: "লাইট থিম", sortTitle: "বিকল্প", sortOptions: "সাজানো", sortNewOld: "নতুন থেকে পুরানো", sortAZ: "নাম অনুযায়ী", sortSize: "আকার অনুযায়ী", actions: "ক্রিয়া", clearTab: "মুছুন", close: "বন্ধ", helpTitle: "সাহায্য", emptyTab: "কোনো রেকর্ড নেই।", selectLanguage: "ভাষা", noSub: "কোনো সাবটাইটেল নেই", autoSeq: "স্বয়ংক্রিয় ক্রম", onlyFirst: "শুধুমাত্র", bestVideo: "সেরা মান", ifNotAvail: "(পাওয়া না গেলে এড়িয়ে যান)", audioOnly: "(শুধুমাত্র অডিও)", audioSub: "(অডিও + সাবটাইটেল)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• মৌলিক ব্যবহার:", helpBasicDesc: "অ্যাপটিতে একটি বেসিক ডাউনলোড ম্যানেজার রয়েছে এবং এটি ইউটিউব ও ইনস্টাগ্রামের মিডিয়া ডাউনলোড করতে পারে। ইউটিউব অ্যাপে শেয়ার করে Ridm নির্বাচন করলে এটি স্বয়ংক্রিয়ভাবে বিশ্লেষিত হয়। আপনি ১০টি লিঙ্ক যোগ করতে পারেন। সেটিংস থেকে ফোল্ডার নির্বাচন বাধ্যতামূলক। সেরা মান নির্বাচন করলে সর্বোচ্চ রেজোলিউশনের ভিডিও ডাউনলোড হবে। ২১৬০p বা ১০৮০p না থাকলে এটি বাদ যাবে। সাবটাইটেল সহ অডিওর জন্য M4A নির্বাচন করুন।", helpBasicWarn: "ব্যাকগ্রাউন্ডে ডাউনলোড প্রক্রিয়া নিরবচ্ছিন্নভাবে চালিয়ে যাওয়ার জন্য, অ্যাপের ব্যাটারি ব্যবহার অ্যান্ড্রয়েড পাওয়ার বিকল্পগুলিতে 'সীমাবদ্ধ নয়' (Unrestricted) এ সেট করতে হবে।",
    helpSmartTitle: "• স্মার্ট ফোল্ডার:", helpSmartDesc: "ধরন অনুযায়ী স্বয়ংক্রিয়ভাবে সাজায়।",
    helpSubTitle: "• সাবটাইটেল পছন্দ:", helpSubDesc: "স্বয়ংক্রিয়ভাবে সাবটাইটেল খুঁজে যুক্ত করবে।",
    helpCookiesTitle: "• প্রমাণীকরণ:", helpCookiesDesc: "cookies.txt ব্যবহার করুন।",
    
    supportTitle: "যোগাযোগ এবং সমর্থন", supportDesc: "Ridm সম্পূর্ণ বিনামূল্যে এবং ওপেন সোর্স। আপনি প্রকল্পটিকে সমর্থন করার জন্য অনুদান দিতে পারেন এবং নিচের ইমেলের মাধ্যমে যোগাযোগ করতে পারেন।", quote: "উদার ব্যক্তির খাবার হলো ওষুধ, আর কৃপণের খাবার হলো রোগ।", donateBtn: "দান করুন", copied: "কপি করা হয়েছে!", copy: "কপি করুন",
    
    exitTitle: "প্রস্থান", exitGraceful: "শেষ করে প্রস্থান", exitForce: "জোরপূর্বক প্রস্থান", errNoInternet: "ইন্টারনেট নেই।", errLocation: "ফোল্ডার নির্বাচন করুন।", errDuplicate: "লিঙ্কটি বিদ্যমান।", errServer: "সার্ভার ত্রুটি।"
  },
  RU: {
    inputPlaceholder: "Вставьте ссылки...", analyzeBtn: "Анализ", activeTab: "АКТИВНЫЕ", finishedTab: "ЗАВЕРШЕННЫЕ", logsTab: "ЖУРНАЛЫ", pauseAll: "Пауза", resumeAll: "Возобновить", analyzingMsg: "Анализ...", optionsLoaded: "Параметры загружены", error: "Ошибка", warning: "Предупреждение", unknown: "Неизвестно", skipped: "ПРОПУЩЕНО", formatSelect: "Формат", subSelect: "Субтитры", tabSelect: "Вкладка", contentCount: "Всего :", rangeSelect: "Диапазон :", downloadAll: "Скачать все", cancel: "Отмена", addToQueue: "В очередь", queued: "В очереди...", downloading: "Загрузка...", paused: "На паузе", completed: "Завершено", open: "Открыть", share: "Поделиться", showInFolder: "В папке", settingsTitle: "Настройки", downloadLoc: "ПАПКА", locNotSet: "Выберите папку", locSet: "Папка установлена", smartFolder: "Умные папки", smartFolderSub: "Авто-сортировка.", maxConcurrent: "ОДНОВРЕМЕННЫЕ", subPref: "ПРИОРИТЕТ СУБТИТРОВ", lang1: "Язык 1", lang2: "Язык 2", lang3: "Язык 3", auth: "АВТОРИЗАЦИЯ", cookiesNotSet: "Выбрать cookies.txt", cookiesSet: "Добавлен", darkTheme: "Тёмная тема", lightTheme: "Светлая тема", sortTitle: "Опции", sortOptions: "СОРТИРОВКА", sortNewOld: "Сначала новые", sortAZ: "По имени", sortSize: "По размеру", actions: "ДЕЙСТВИЯ", clearTab: "Очистить вкладку", close: "Закрыть", helpTitle: "Справка", emptyTab: "Нет записей.", selectLanguage: "Язык", noSub: "Без субтитров", autoSeq: "Автопоследовательность", onlyFirst: "Только", bestVideo: "Лучшее качество", ifNotAvail: "(Пропустить, если нет)", audioOnly: "(Только аудио)", audioSub: "(Аудио + Субтитры)", slogan: "Raid - inspect - download - manage",
    helpBasicTitle: "• Использование:", helpBasicDesc: "Приложение включает базовый менеджер загрузок и загружает медиа с YouTube и Instagram. При нажатии «поделиться» в YouTube и выборе Ridm ссылка анализируется автоматически. Можно добавить до 10 ссылок. Нужно выбрать папку загрузки в настройках. 'Лучшее качество' загружает видео максимального разрешения. Если 2160p или 1080p отсутствует, файл пропускается. Для аудио с субтитрами выбирайте M4A.", helpBasicWarn: "Чтобы процесс загрузки продолжался непрерывно в фоновом режиме, использование батареи приложения должно быть установлено на «Без ограничений» в параметрах питания Android.",
    helpSmartTitle: "• Умные папки:", helpSmartDesc: "Автоматически сортирует загрузки.",
    helpSubTitle: "• Приоритет субтитров:", helpSubDesc: "Система автоматически найдет и встроит субтитры.",
    helpCookiesTitle: "• Авторизация:", helpCookiesDesc: "Используйте cookies.txt для контента с возрастными ограничениями.",
    
    supportTitle: "Связь и поддержка", supportDesc: "Ridm полностью бесплатен и имеет открытый исходный код. Вы можете сделать пожертвование на развитие проекта и связаться с нами по почте.", quote: "Пища щедрого — лекарство, пища скупого — болезнь.", donateBtn: "Пожертвовать", copied: "Скопировано!", copy: "Копировать",
    
    exitTitle: "Выход", exitGraceful: "Завершить и выйти", exitForce: "Принудительный выход", errNoInternet: "Нет интернета.", errLocation: "Выберите папку.", errDuplicate: "Ссылка существует.", errServer: "Ошибка сервера."
  }
};